dist: xenial
language: node_js
node_js:
    - 10
before_install:
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
    - export PATH=~/npm/node_modules/.bin:$PATH
install:
    - npm install
    - npm install -g serve
script:
    - npm run build
deploy:
    - provider: script
      script: bash scripts/deploy.sh
      on:
          branch: master
