stages:
  - lint
  - name: integration test 
    branches:
      only:
        - master
        - release
        - hotfix
  - name: unit test
    branches:
      only:
        - develop
  - name: deploy
    branches:
      only:
        - master

dist: xenial
language: node_js
node_js:
  - 12
env:
  - CI=false
before_install:
  - export PATH=~/npm/node_modules/.bin:$PATH
install:
  - npm install
script:
  - npm run build

jobs:
  include:
    - stage: lint
      name: "Linting"
      script:
        - npm start lint

    - stage: integration test
      name: "integration test"
      script: 
        - npm start test.integration

    - stage: unit test
      name: "unit test"
      script: 
        - npm start test.unit
