stages:
  - lint
  - name: integration test 
    if: branch in (master, release, hotfix)
  - name: unit test
    if: branch = develop
  - name: deploy
    if: branch = master
  - name: others
    if: branch != master

dist: xenial
language: node_js
node_js:
  - 12
env:
  - CI=false
before_install:
  - export PATH=~/npm/node_modules/.bin:$PATH
install:
  - npm install
script:
  - npm run build

jobs:
  include:
    - stage: lint
      name: "Linting"
      script:
        - npm start lint

    - stage: integration test
      name: "integration test"
      script: 
        - npm start test.integration

    - stage: unit test
      name: "unit test"
      script: 
        - npm start test.unit
    
    - stage: deploy
      name: "deploy"
      script:
        - echo "deploy!"

    - stage: others
      name: "others"
      script:
        - echo "others!"
